-- Generated by generate_schema.py. Do not edit.

CREATE TABLE mixtape (
	id SERIAL NOT NULL, 
	stack_auth_user_id VARCHAR, 
	public_id VARCHAR NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	intro_text VARCHAR, 
	subtitle1 VARCHAR(60), 
	subtitle2 VARCHAR(60), 
	subtitle3 VARCHAR(60), 
	is_public BOOLEAN NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	version INTEGER NOT NULL, 
	undo_to_version INTEGER, 
	redo_to_version INTEGER, 
	resembles_version INTEGER, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_mixtape_stack_auth_user_id ON mixtape (stack_auth_user_id);

CREATE UNIQUE INDEX ix_mixtape_public_id ON mixtape (public_id);

CREATE INDEX ix_mixtape_stack_auth_user_id_last_modified_time ON mixtape (stack_auth_user_id, last_modified_time);

CREATE TABLE mixtape_snapshot (
	id SERIAL NOT NULL, 
	mixtape_id INTEGER NOT NULL, 
	public_id VARCHAR NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	intro_text VARCHAR, 
	subtitle1 VARCHAR(60), 
	subtitle2 VARCHAR(60), 
	subtitle3 VARCHAR(60), 
	is_public BOOLEAN NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	version INTEGER NOT NULL, 
	stack_auth_user_id VARCHAR, 
	undo_to_version INTEGER, 
	redo_to_version INTEGER, 
	resembles_version INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT distinct_versions UNIQUE (mixtape_id, version), 
	FOREIGN KEY(mixtape_id) REFERENCES mixtape (id)
);

CREATE INDEX ix_mixtape_snapshot_public_id ON mixtape_snapshot (public_id);

CREATE TABLE mixtape_track (
	id SERIAL NOT NULL, 
	mixtape_id INTEGER NOT NULL, 
	track_position INTEGER NOT NULL, 
	track_text VARCHAR, 
	spotify_uri VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT mixtape_track_unique_position UNIQUE (mixtape_id, track_position), 
	FOREIGN KEY(mixtape_id) REFERENCES mixtape (id)
);

CREATE TABLE mixtape_snapshot_track (
	id SERIAL NOT NULL, 
	mixtape_snapshot_id INTEGER NOT NULL, 
	track_position INTEGER NOT NULL, 
	track_text VARCHAR, 
	spotify_uri VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(mixtape_snapshot_id) REFERENCES mixtape_snapshot (id)
);

