-- Generated by generate_schema.py. Do not edit.

CREATE TABLE "Mixtape" (
	id SERIAL NOT NULL, 
	stack_auth_user_id VARCHAR NOT NULL, 
	public_id VARCHAR NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	intro_text VARCHAR, 
	is_public BOOLEAN NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	version INTEGER NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "ix_Mixtape_public_id" ON "Mixtape" (public_id);

CREATE INDEX ix_mixtape_stack_auth_user_id_last_modified_time ON "Mixtape" (stack_auth_user_id, last_modified_time);

CREATE UNIQUE INDEX "ix_Mixtape_public_id" ON "Mixtape" (public_id);

CREATE INDEX "ix_Mixtape_stack_auth_user_id" ON "Mixtape" (stack_auth_user_id);

CREATE TABLE "MixtapeAudit" (
	id SERIAL NOT NULL, 
	mixtape_id INTEGER NOT NULL, 
	public_id VARCHAR NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	intro_text VARCHAR, 
	is_public BOOLEAN NOT NULL, 
	create_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	version INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(mixtape_id) REFERENCES "Mixtape" (id)
);

CREATE INDEX "ix_MixtapeAudit_public_id" ON "MixtapeAudit" (public_id);

CREATE TABLE "MixtapeTrack" (
	id SERIAL NOT NULL, 
	mixtape_id INTEGER NOT NULL, 
	track_position INTEGER NOT NULL, 
	track_text VARCHAR, 
	spotify_uri VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT mixtape_track_unique_position UNIQUE (mixtape_id, track_position), 
	FOREIGN KEY(mixtape_id) REFERENCES "Mixtape" (id)
);

CREATE TABLE "MixtapeAuditTrack" (
	id SERIAL NOT NULL, 
	mixtape_audit_id INTEGER NOT NULL, 
	track_position INTEGER NOT NULL, 
	track_text VARCHAR, 
	spotify_uri VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(mixtape_audit_id) REFERENCES "MixtapeAudit" (id)
);

