import os
import sys
import argparse
from sqlmodel import SQLModel
from sqlalchemy import create_mock_engine

# Add the project root to the path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Import models to ensure they're registered with SQLModel metadata
import backend.db_models # noqa: F401

parser = argparse.ArgumentParser()
parser.add_argument('--output', default='schema.gen.sql', help='Output file for generated schema')
args = parser.parse_args()

with open(args.output, 'w') as f:
    f.write("-- Generated by generate_schema.py. Do not edit.\n\n")

    def metadata_dump(sql, *multiparams, **params):
        f.write(str(sql.compile(dialect=engine.dialect)).strip() + ";\n\n")

    # Create a mock engine that captures SQL statements
    database_url = "postgresql+psycopg2://"
    engine = create_mock_engine(database_url, metadata_dump)
    SQLModel.metadata.create_all(engine)
